version: '3.8'

services:
  my_api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Monta el directorio actual (.) en el contenedor
    networks:
      - my_network

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf  # Montar archivo de configuración
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
